name: 'Jekyll Deploy Action'
description: >
  A Github Action to deploy the Jekyll site conveniently for GitHub Pages
inputs:
  provider:
    description: 'The deploy provider'
    required: true
  owner:
    description: 'The deploy owner'
    required: false
  token:
    description: 'The deploy token'
    required: false
  credentials:
    description: 'The gcloud credentials'
    required: true
  repository:
    description: 'The deploy repository'
    required: false
  branch:
    description: 'The deploy branch'
    required: false
  actor:
    description: 'The github username creating the commit'
    required: false
  cname:
    description: 'The cname to use for the site'
    required: false
  bundler_ver:
    description: 'The Bundler version'
    required: false
  jekyll_baseurl:
    description: 'The Jekyll website baseurl'
    required: false
  pre_build_commands:
    description: 'The pre-build commands'
    required: false

branding:
  icon: 'command'
  color: 'red'
  
runs:
  using: composite
  steps:
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ${{ github.workspace }}/_site
